spring.application.name=rewards-program
server.port=8080
logging.level.com.charter.reward=INFO
spring.task.execution.pool.core-size=2
spring.task.execution.pool.max-size=4
spring.task.execution.pool.queue-capacity=100
spring.task.execution.thread-name-prefix=rewards-async-
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
